<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SitePropertyRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * 
 */
class SitePropertyRepository extends EntityRepository
{
    public function getSiteProperties($group) 
    {
       $builder =  $this->createQueryBuilder('p');
       return  $builder->where('p.group = :group_name')
               ->setParameter('group_name', $group)
               ->getQuery()->getResult();
                
    }
    
}
